#include <catch2/catch_test_macros.hpp>

#include <woki/gfx/advanced.hpp>

namespace {
woki::gfx::ShaderDescriptor Descriptor(std::string_view source) {
    woki::gfx::ShaderDescriptor descriptor;
    descriptor.name = "test";
    descriptor.sources.push_back(*woki::asset::AssetPath::Parse(source));
    descriptor.entry_points.push_back({woki::gfx::ShaderStage::Vertex, "main"});
    return descriptor;
}
} // namespace

TEST_CASE("Source composition lexes exact includes and maps generated bytes") {
    auto mount = woki::createRef<woki::asset::MemoryMount>();
    mount->PutText(*woki::asset::AssetPath::Parse("shaders/main.wgsl"), "// #include \"ignored.wgsl\"\nlet s = \"#include \\\"ignored.wgsl\\\"\";\n#include \"parts/common.wgsl\"\n@vertex fn main() {}\n");
    mount->PutText(*woki::asset::AssetPath::Parse("shaders/parts/common.wgsl"), "const common = 1;\n");
    woki::asset::Vfs vfs;
    vfs.AddMount(mount);
    const auto composed = woki::gfx::ShaderSourceResolver(vfs).Compose(Descriptor("shaders/main.wgsl"));
    CHECK(composed.diagnostics.empty());
    CHECK(composed.dependencies.size() == 2);
    CHECK(composed.code.find("const common = 1") != std::string::npos);
    const auto offset = composed.code.find("const common");
    const auto mapped = woki::gfx::MapGeneratedRange(composed, offset, 5);
    REQUIRE(mapped.path);
    CHECK(mapped.path->String() == "shaders/parts/common.wgsl");
}

TEST_CASE("Source composition rejects traversal and canonical include cycles") {
    auto mount = woki::createRef<woki::asset::MemoryMount>();
    mount->PutText(*woki::asset::AssetPath::Parse("a/main.wgsl"), "#include \"../escape.wgsl\"\n#include \"loop.wgsl\"\n");
    mount->PutText(*woki::asset::AssetPath::Parse("a/loop.wgsl"), "#include \"main.wgsl\"\n");
    woki::asset::Vfs vfs;
    vfs.AddMount(mount);
    const auto composed = woki::gfx::ShaderSourceResolver(vfs).Compose(Descriptor("a/main.wgsl"));
    REQUIRE(composed.diagnostics.size() == 2);
    CHECK(composed.diagnostics[0].code == "SHD2002");
    CHECK(composed.diagnostics[1].code == "SHD2003");
}

TEST_CASE("Source composition handles nested comments and emits shared modules once") {
    auto mount = woki::createRef<woki::asset::MemoryMount>();
    mount->PutText(*woki::asset::AssetPath::Parse("main.wgsl"), "/* outer /* nested */ #include \"ignored.wgsl\" */\n#include \"left.wgsl\"\n#include \"right.wgsl\"\n");
    mount->PutText(*woki::asset::AssetPath::Parse("left.wgsl"), "#include \"shared.wgsl\"\nconst left = shared;\n");
    mount->PutText(*woki::asset::AssetPath::Parse("right.wgsl"), "#include \"shared.wgsl\"\nconst right = shared;\n");
    mount->PutText(*woki::asset::AssetPath::Parse("shared.wgsl"), "const shared = 1;\n");
    woki::asset::Vfs vfs;
    vfs.AddMount(mount);
    auto descriptor = Descriptor("main.wgsl");
    descriptor.sources.push_back(*woki::asset::AssetPath::Parse("shared.wgsl"));
    const auto descriptor_path = *woki::asset::AssetPath::Parse("shader.woki-shader");
    const auto composed = woki::gfx::ShaderSourceResolver(vfs).Compose(descriptor, descriptor_path);
    CHECK(composed.diagnostics.empty());
    CHECK(composed.dependencies.size() == 5);
    CHECK(composed.dependencies.front() == *woki::asset::AssetPath::Parse("left.wgsl"));
    const auto declaration = composed.code.find("const shared = 1");
    REQUIRE(declaration != std::string::npos);
    CHECK(composed.code.find("const shared = 1", declaration + 1) == std::string::npos);
    CHECK(std::ranges::none_of(composed.dependencies, [](const auto& path) { return path.String() == "ignored.wgsl"; }));
}
