if(NOT DEFINED PROJECT_DIR OR NOT DEFINED SDK_DIR OR NOT DEFINED STATE_FILE)
    message(FATAL_ERROR "PROJECT_DIR, SDK_DIR, and STATE_FILE are required")
endif()
if(NOT EXISTS "${STATE_FILE}")
    message(FATAL_ERROR "Staged extension package has no content state")
endif()

include("${CMAKE_CURRENT_LIST_DIR}/ExtensionInputHash.cmake")
file(STRINGS "${STATE_FILE}" state_lines)
foreach(line IN LISTS state_lines)
    if(line MATCHES "^input=([0-9a-f]+)$")
        set(expected_hash "${CMAKE_MATCH_1}")
    elseif(line MATCHES "^hash=(.*)$")
        list(APPEND expected_records "${CMAKE_MATCH_1}")
    endif()
endforeach()
if(NOT DEFINED expected_hash)
    message(FATAL_ERROR "Staged extension package has invalid content state")
endif()
woki_extension_input_hash("${PROJECT_DIR}" "${SDK_DIR}" actual_hash actual_records)
if(NOT actual_hash STREQUAL expected_hash)
    foreach(record IN LISTS expected_records)
        if(NOT record IN_LIST actual_records)
            string(REGEX REPLACE "=([0-9a-f]+)$" "" changed "${record}")
            message(FATAL_ERROR "Staged extension package is stale; rebuild after changing ${changed}")
        endif()
    endforeach()
    foreach(record IN LISTS actual_records)
        if(NOT record IN_LIST expected_records)
            string(REGEX REPLACE "=([0-9a-f]+)$" "" changed "${record}")
            message(FATAL_ERROR "Staged extension package is stale; rebuild after adding ${changed}")
        endif()
    endforeach()
    message(FATAL_ERROR "Staged extension package is stale; rebuild after adding source, assets, or SDK content")
endif()
