function(woki_extension_input_hash source_dir sdk_dir output)
    file(GLOB_RECURSE _project_candidates LIST_DIRECTORIES FALSE "${source_dir}/*")
    set(_project_inputs)
    foreach(_input IN LISTS _project_candidates)
        file(RELATIVE_PATH _relative "${source_dir}" "${_input}")
        if(NOT _relative MATCHES "^build/" AND NOT _relative STREQUAL "compile_commands.json")
            list(APPEND _project_inputs "${_input}")
        endif()
    endforeach()
    file(GLOB_RECURSE _sdk_inputs LIST_DIRECTORIES FALSE
        "${sdk_dir}/woki/extension.hpp"
        "${sdk_dir}/woki/extension/*"
        "${sdk_dir}/woki/ext/sdk/*"
        "${sdk_dir}/woki/math/*"
        "${sdk_dir}/woki/ecs/guest.hpp"
    )
    set(_guest_root "${sdk_dir}/../../")
    file(GLOB_RECURSE _guest_inputs LIST_DIRECTORIES FALSE
        "${_guest_root}/math/include/woki/math/*"
        "${_guest_root}/ecs/include/woki/ecs/guest.hpp"
    )
    set(_records)
    foreach(_input IN LISTS _project_inputs)
        if(IS_SYMLINK "${_input}")
            message(FATAL_ERROR "Extension inputs may not be symbolic links: ${_input}")
        endif()
        file(SHA256 "${_input}" _hash)
        file(RELATIVE_PATH _relative "${source_dir}" "${_input}")
        list(APPEND _records "project/${_relative}=${_hash}")
    endforeach()
    foreach(_input IN LISTS _sdk_inputs)
        if(IS_SYMLINK "${_input}")
            message(FATAL_ERROR "Extension inputs may not be symbolic links: ${_input}")
        endif()
        file(SHA256 "${_input}" _hash)
        file(RELATIVE_PATH _relative "${sdk_dir}" "${_input}")
        list(APPEND _records "sdk/${_relative}=${_hash}")
    endforeach()
    foreach(_input IN LISTS _guest_inputs)
        if(IS_SYMLINK "${_input}")
            message(FATAL_ERROR "Extension guest library inputs may not be symbolic links: ${_input}")
        endif()
        file(SHA256 "${_input}" _hash)
        file(RELATIVE_PATH _relative "${_guest_root}" "${_input}")
        list(APPEND _records "guest/${_relative}=${_hash}")
    endforeach()
    list(SORT _records)
    string(JOIN "\n" _content ${_records})
    string(SHA256 _result "${_content}")
    set(${output} "${_result}" PARENT_SCOPE)
    if(ARGC GREATER 3)
        set(${ARGV3} "${_records}" PARENT_SCOPE)
    endif()
endfunction()
