function(woki_extension_manifest_wasm manifest output)
    file(STRINGS "${manifest}" _manifest_lines)
    set(_in_runtime FALSE)
    set(_wasm "")
    foreach(_line IN LISTS _manifest_lines)
        if(_line MATCHES "^[ ]*runtime:[ ]*(#.*)?$")
            set(_in_runtime TRUE)
        elseif(_in_runtime AND _line MATCHES "^[ ]+wasm:[ ]*([^#]+)")
            set(_wasm "${CMAKE_MATCH_1}")
            string(STRIP "${_wasm}" _wasm)
            if(_wasm MATCHES "^'(.*)'$" OR _wasm MATCHES "^\"(.*)\"$")
                set(_wasm "${CMAKE_MATCH_1}")
            endif()
            break()
        elseif(_in_runtime AND _line MATCHES "^[^ ]")
            break()
        endif()
    endforeach()
    if(_wasm STREQUAL "" OR IS_ABSOLUTE "${_wasm}" OR _wasm MATCHES "(^|/)\.\.?(/|$)" OR _wasm MATCHES "[/]{2}|[:;\\\\]")
        message(FATAL_ERROR "runtime.wasm must be a safe relative path in ${manifest}")
    endif()
    set(${output} "${_wasm}" PARENT_SCOPE)
endfunction()
