function(woki_extension_manifest_wasm manifest output)
    file(STRINGS "${manifest}" _manifest_lines)
    set(_in_runtime FALSE)
    set(_wasm "")
    foreach(_line IN LISTS _manifest_lines)
        if(_line MATCHES "^[ ]*runtime:[ ]*(#.*)?$")
            set(_in_runtime TRUE)
        elseif(_in_runtime AND _line MATCHES "^[ ]+wasm:[ ]*([^#]+)")
            set(_wasm "${CMAKE_MATCH_1}")
            string(STRIP "${_wasm}" _wasm)
            if(_wasm MATCHES "^'(.*)'$" OR _wasm MATCHES "^\"(.*)\"$")
                set(_wasm "${CMAKE_MATCH_1}")
            endif()
            break()
        elseif(_in_runtime AND _line MATCHES "^[^ ]")
            break()
        endif()
    endforeach()
    if(_wasm STREQUAL "" OR IS_ABSOLUTE "${_wasm}" OR _wasm MATCHES "(^|/)\.\.?(/|$)" OR _wasm MATCHES "[/]{2}|[:;\\\\]")
        message(FATAL_ERROR "runtime.wasm must be a safe relative path in ${manifest}")
    endif()
    set(${output} "${_wasm}" PARENT_SCOPE)
endfunction()

function(woki_extension_manifest_permissions manifest output)
    file(STRINGS "${manifest}" _manifest_lines)
    set(_permissions)
    set(_in_permissions FALSE)
    foreach(_line IN LISTS _manifest_lines)
        if(_line MATCHES "^[ ]*permissions:[ ]*\\[([^]]*)\\][ ]*(#.*)?$")
            set(_inline "${CMAKE_MATCH_1}")
            string(REPLACE "," ";" _inline "${_inline}")
            foreach(_permission IN LISTS _inline)
                string(STRIP "${_permission}" _permission)
                string(REGEX REPLACE "^['\"]|['\"]$" "" _permission "${_permission}")
                if(NOT _permission STREQUAL "")
                    list(APPEND _permissions "${_permission}")
                endif()
            endforeach()
            break()
        elseif(_line MATCHES "^[ ]*permissions:[ ]*(#.*)?$")
            set(_in_permissions TRUE)
        elseif(_line MATCHES "^[ ]*permissions:")
            message(FATAL_ERROR "Manifest permissions must be a YAML sequence in ${manifest}")
        elseif(_in_permissions AND _line MATCHES "^[ ]*-[ ]*([^#]+)")
            set(_permission "${CMAKE_MATCH_1}")
            string(STRIP "${_permission}" _permission)
            string(REGEX REPLACE "^['\"]|['\"]$" "" _permission "${_permission}")
            list(APPEND _permissions "${_permission}")
        elseif(_in_permissions AND _line MATCHES "^[^ ]")
            break()
        endif()
    endforeach()

    set(_supported log paths storage config events)
    set(_seen)
    foreach(_permission IN LISTS _permissions)
        if(NOT _permission IN_LIST _supported)
            message(FATAL_ERROR "Unsupported manifest permission '${_permission}' in ${manifest}")
        endif()
        if(_permission IN_LIST _seen)
            message(FATAL_ERROR "Duplicate manifest permission '${_permission}' in ${manifest}")
        endif()
        list(APPEND _seen "${_permission}")
    endforeach()
    set(${output} "${_permissions}" PARENT_SCOPE)
endfunction()

function(woki_extension_manifest_libraries manifest output)
    file(STRINGS "${manifest}" _manifest_lines)
    set(_libraries)
    set(_in_libraries FALSE)
    foreach(_line IN LISTS _manifest_lines)
        if(_line MATCHES "^[ ]*libraries:[ ]*\\[([^]]*)\\][ ]*(#.*)?$")
            set(_inline "${CMAKE_MATCH_1}")
            string(REPLACE "," ";" _inline "${_inline}")
            foreach(_library IN LISTS _inline)
                string(STRIP "${_library}" _library)
                string(REGEX REPLACE "^['\"]|['\"]$" "" _library "${_library}")
                if(NOT _library STREQUAL "")
                    list(APPEND _libraries "${_library}")
                endif()
            endforeach()
            break()
        elseif(_line MATCHES "^[ ]*libraries:[ ]*(#.*)?$")
            set(_in_libraries TRUE)
        elseif(_line MATCHES "^[ ]*libraries:")
            message(FATAL_ERROR "Manifest libraries must be a YAML sequence in ${manifest}")
        elseif(_in_libraries AND _line MATCHES "^[ ]*-[ ]*([^#]+)")
            set(_library "${CMAKE_MATCH_1}")
            string(STRIP "${_library}" _library)
            string(REGEX REPLACE "^['\"]|['\"]$" "" _library "${_library}")
            list(APPEND _libraries "${_library}")
        elseif(_in_libraries AND _line MATCHES "^[^ ]")
            break()
        endif()
    endforeach()

    set(_seen)
    foreach(_library IN LISTS _libraries)
        if(NOT _library STREQUAL "math" AND NOT _library STREQUAL "ecs")
            message(FATAL_ERROR "Unsupported manifest library '${_library}' in ${manifest}; supported libraries are math and ecs")
        endif()
        if(_library IN_LIST _seen)
            message(FATAL_ERROR "Duplicate manifest library '${_library}' in ${manifest}")
        endif()
        list(APPEND _seen "${_library}")
    endforeach()
    set(${output} "${_libraries}" PARENT_SCOPE)
endfunction()
