if(NOT DEFINED SOURCE_DIR OR NOT DEFINED DESTINATION_DIR OR NOT DEFINED SOURCE_MANIFEST OR NOT DEFINED PROJECT_DIR OR NOT DEFINED SDK_DIR OR NOT DEFINED CONFIG)
    message(FATAL_ERROR "SOURCE_DIR, DESTINATION_DIR, SOURCE_MANIFEST, PROJECT_DIR, SDK_DIR, and CONFIG are required")
endif()

set(PACKAGE_DIR "${SOURCE_DIR}")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyExtensionPackage.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ExtensionInputHash.cmake")
woki_extension_input_hash("${PROJECT_DIR}" "${SDK_DIR}" input_hash input_records)

string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef token)
set(staging "${DESTINATION_DIR}.tmp-${token}")
set(backup "${DESTINATION_DIR}.old-${token}")
file(REMOVE_RECURSE "${staging}" "${backup}")
file(MAKE_DIRECTORY "${staging}")
file(COPY "${SOURCE_DIR}/" DESTINATION "${staging}")
file(GLOB_RECURSE staged_entries LIST_DIRECTORIES TRUE "${staging}/*")
foreach(entry IN LISTS staged_entries)
    if(IS_SYMLINK "${entry}")
        file(REMOVE_RECURSE "${staging}")
        message(FATAL_ERROR "Staged extension packages may not contain symbolic links: ${entry}")
    endif()
endforeach()
set(PACKAGE_DIR "${staging}")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyExtensionPackage.cmake")
file(SHA256 "${SOURCE_MANIFEST}" manifest_hash)
set(state_staging "${DESTINATION_DIR}.state.tmp-${token}")
file(WRITE "${state_staging}"
    "config=${CONFIG}\nmanifest=${manifest_hash}\ninput=${input_hash}\n")
foreach(record IN LISTS input_records)
    file(APPEND "${state_staging}" "hash=${record}\n")
endforeach()
if(EXISTS "${DESTINATION_DIR}")
    file(RENAME "${DESTINATION_DIR}" "${backup}" RESULT rename_old)
    if(rename_old)
        file(REMOVE_RECURSE "${staging}")
        file(REMOVE "${state_staging}")
        message(FATAL_ERROR "Cannot preserve previous staged package: ${rename_old}")
    endif()
endif()
file(RENAME "${staging}" "${DESTINATION_DIR}" RESULT rename_new)
if(rename_new)
    if(EXISTS "${backup}")
        file(RENAME "${backup}" "${DESTINATION_DIR}")
    endif()
    file(REMOVE_RECURSE "${staging}")
    file(REMOVE "${state_staging}")
    message(FATAL_ERROR "Cannot activate staged package: ${rename_new}")
endif()
file(RENAME "${state_staging}" "${DESTINATION_DIR}.state" RESULT state_rename)
if(state_rename)
    file(REMOVE "${state_staging}")
    file(REMOVE_RECURSE "${DESTINATION_DIR}")
    if(EXISTS "${backup}")
        file(RENAME "${backup}" "${DESTINATION_DIR}")
    endif()
    message(FATAL_ERROR "Cannot activate staged package state: ${state_rename}")
endif()
file(REMOVE_RECURSE "${backup}")
