if(NOT DEFINED SOURCE_DIR OR NOT DEFINED DESTINATION_DIR OR NOT DEFINED SOURCE_MANIFEST OR NOT DEFINED PROJECT_DIR OR NOT DEFINED SDK_DIR OR NOT DEFINED CONFIG)
    message(FATAL_ERROR "SOURCE_DIR, DESTINATION_DIR, SOURCE_MANIFEST, PROJECT_DIR, SDK_DIR, and CONFIG are required")
endif()

set(PACKAGE_DIR "${SOURCE_DIR}")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyExtensionPackage.cmake")
include("${CMAKE_CURRENT_LIST_DIR}/ExtensionInputHash.cmake")
woki_extension_input_hash("${PROJECT_DIR}" "${SDK_DIR}" input_hash input_records)

get_filename_component(destination_parent "${DESTINATION_DIR}" DIRECTORY)
file(MAKE_DIRECTORY "${destination_parent}")
file(LOCK "${DESTINATION_DIR}.lock" GUARD PROCESS TIMEOUT 120 RESULT_VARIABLE lock_result)
if(lock_result)
    message(FATAL_ERROR "Cannot lock staged extension package: ${lock_result}")
endif()

string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef token)
set(staging "${DESTINATION_DIR}.tmp-${token}")
set(backup "${DESTINATION_DIR}.old-${token}")
file(REMOVE_RECURSE "${staging}" "${backup}")

# Recover an interrupted publish before creating the next transaction.
file(GLOB stale_backups LIST_DIRECTORIES TRUE "${DESTINATION_DIR}.old-*")
file(GLOB stale_staging LIST_DIRECTORIES TRUE "${DESTINATION_DIR}.tmp-*")
list(SORT stale_backups)
if(NOT EXISTS "${DESTINATION_DIR}" AND stale_backups)
    list(POP_BACK stale_backups recover_backup)
    file(RENAME "${recover_backup}" "${DESTINATION_DIR}" RESULT recover_result)
    if(recover_result)
        message(FATAL_ERROR "Cannot recover previous staged package: ${recover_result}")
    endif()
endif()
foreach(stale_backup IN LISTS stale_backups)
    file(REMOVE_RECURSE "${stale_backup}")
endforeach()
foreach(stale_stage IN LISTS stale_staging)
    file(REMOVE_RECURSE "${stale_stage}")
endforeach()

file(MAKE_DIRECTORY "${staging}")
file(COPY "${SOURCE_DIR}/" DESTINATION "${staging}")
file(GLOB_RECURSE staged_entries LIST_DIRECTORIES TRUE "${staging}/*")
foreach(entry IN LISTS staged_entries)
    if(IS_SYMLINK "${entry}")
        file(REMOVE_RECURSE "${staging}")
        message(FATAL_ERROR "Staged extension packages may not contain symbolic links: ${entry}")
    endif()
endforeach()
set(PACKAGE_DIR "${staging}")
include("${CMAKE_CURRENT_LIST_DIR}/VerifyExtensionPackage.cmake")
file(SHA256 "${SOURCE_MANIFEST}" manifest_hash)
set(state_staging "${staging}/.woki-state")
file(WRITE "${state_staging}"
    "config=${CONFIG}\nmanifest=${manifest_hash}\ninput=${input_hash}\n")
foreach(record IN LISTS input_records)
    file(APPEND "${state_staging}" "hash=${record}\n")
endforeach()
if(EXISTS "${DESTINATION_DIR}")
    file(RENAME "${DESTINATION_DIR}" "${backup}" RESULT rename_old)
    if(rename_old)
        file(REMOVE_RECURSE "${staging}")
        message(FATAL_ERROR "Cannot preserve previous staged package: ${rename_old}")
    endif()
endif()
file(RENAME "${staging}" "${DESTINATION_DIR}" RESULT rename_new)
if(rename_new)
    if(EXISTS "${backup}")
        file(RENAME "${backup}" "${DESTINATION_DIR}" RESULT rollback_result)
        if(rollback_result)
            message(FATAL_ERROR "Cannot activate staged package (${rename_new}) and cannot restore the previous package (${rollback_result})")
        endif()
    endif()
    file(REMOVE_RECURSE "${staging}")
    message(FATAL_ERROR "Cannot activate staged package: ${rename_new}")
endif()
file(REMOVE "${DESTINATION_DIR}.state")
file(REMOVE_RECURSE "${backup}")
