if(NOT DEFINED LINK OR NOT DEFINED TARGET)
    message(FATAL_ERROR "LINK and TARGET are required")
endif()
if(NOT EXISTS "${LINK}")
    message(FATAL_ERROR "Developer executable link is missing: ${LINK}")
endif()

if(WIN32)
    file(SHA256 "${LINK}" link_hash)
    file(SHA256 "${TARGET}" target_hash)
    if(NOT link_hash STREQUAL target_hash)
        message(FATAL_ERROR "Developer executable copy is stale: ${LINK}")
    endif()
else()
    if(NOT IS_SYMLINK "${LINK}")
        message(FATAL_ERROR "Developer executable is not a symbolic link: ${LINK}")
    endif()
    file(REAL_PATH "${LINK}" link_real)
    file(REAL_PATH "${TARGET}" target_real)
    if(NOT link_real STREQUAL target_real)
        message(FATAL_ERROR "Developer link targets ${link_real}, expected ${target_real}")
    endif()
endif()
